### ISSUE TITLE
Remove PHP version check

### ISSUE THREAD

**Issue by pdclark** [pdclark/git-plugin-updates#12]
See https://github.com/afragen/github-updater/issues/2#issuecomment-27449092

Quoting @GaryJones:

> It's completely redundant. The WP bootstrap process is:
> 
> Request gets directed to index.php
> - ...which requires wp-blog-header.php
> - ...which requires wp-load.php
> - ...which calls wp_check_php_mysql_versions()
> - ...which does a check against the PHP version and dies if it at least the required level.

**Comment by pdclark** [comment]
It is redundant since WordPress 3.2... The check is being extra cautious in case anyone tries to install on `< 3.2`. (`wp_check_php_mysql_version()` checks `$required_php_version`, which was [set to 5.2.4 in WP 3.2](https://github.com/WordPress/WordPress/commit/d36a6d3d6cf70c287c61b5b073804b90864034f7).

At the same time... WordPress does provide a `Requires` header for a minimum WP version.

I'd take any of these as a good reason to drop it completely:
- A `Requires` header actually does something that prevents a plugin from being activated.
- No one... I mean almost NO ONE is running WordPress < 3.2. [Install stats](http://wordpress.org/about/stats/) show 25% on `3.0` (omg, so sad!)... but it doesn't show anything on PHP 4. I'm asking around to see if that can possibly be true. (EDIT: [Otto says](https://twitter.com/otto42/status/395708229508157440) they just don't collect stats for lower versions.)

If neither of those pan out, I'd still be open to cleaning up `plugin.php` by doing a WordPress version check, and only including the function from a file if it's < `3.2`.

Sorry to be so pedantic about it. My goal is pretty much to never, ever, ever get a support request or tweet that says, "your plugin crashed my site"... even in cases of extreme negligence.

**Comment by afragen** [comment]
How about a stern warning in the README that says don't use if you're a slug and don't keep your WP install up to date, or at least 2 point versions old

Can always do a version check and return false very early.

**Comment by pdclark** [comment]
**README:** Seems to me that a message in the readme would be read by people who care and update, but wouldn't be useful to them... and would be not read by people who don't care and don't update... not fixing their issue.

**Version check**: I'm open to just doing a WP version check — that'd certainly clean up the file. I'd still prefer to include a file containing the message, upgrade instructions, and plugin deactivate logic rather than just return false. That's a point at which we'd have the undivided attention of the slugs to tell them, "look bucko! you need to shape up or ship out!". I'd like to take that opportunity. :)

**Comment by GaryJones** [comment]
If someone is looking to install plugins that update from outside of the typical wp.org repo, then they are going to be experienced enough to know to keep WP more up to date than 3.2. Either way, it's a corner case at best, not your problem to solve, and well outside the scope and _responsibility_ of individual plugins to be making version checks against the minimum PHP version required for WP itself.

Your "extra cautious" means that you're getting `100% - almost no-one` to go through at least one extra function call, just to cater for the `almost no-one` who probably aren't running this plugin anyway.

**Comment by afragen** [comment]
Should be easy enough to check version add an admin_notice and deactivate.

**Comment by pdclark** [comment]
Yup — that's [the current logic](https://github.com/brainstormmedia/git-plugin-updates/blob/master/plugin.php#L62)

**Comment by pdclark** [comment]
What do you think of [that solution](https://github.com/brainstormmedia/git-plugin-updates/commit/dfefc85e0218c365e49e84ce0763cfe21403a884)?

**Comment by GaryJones** [comment]
I disagree with having it in completely. It's an out of scope solution for a corner case, for a target audience who wouldn't be using this plugin anyway.

The sites that are reporting as 3.0 etc. are more than likely abandoned - so they're not going to be installing this plugin anyway.

**Comment by afragen** [comment]
> I disagree with having it in completely. It's an out of scope solution for a corner case, for a target audience who wouldn't be using this plugin anyway.
> 
> The sites that are reporting as 3.0 etc. are more than likely abandoned - so they're not going to be installing this plugin anyway.

I have to agree. Anyone installing this plugin won't be having this issue. I've never had anyone remotely tell me github-updater was crashing their site.

**Comment by pdclark** [comment]
I've been thinking about this over dinner and meeting and think I have my thoughts organized, but I want to check validity of my assumptions first (quantify if this really matters for any sites or not). I'll reply shortly.

**Comment by pdclark** [comment]
## Scope

#### How many installs will this check effect?

`72,400,000` WordPress sites `*` `50%` self-hosted = `36,200,000` sites total [source - yoast](http://yoast.com/wordpress-stats/)

`28%` of sites running WP `3.0` or `3.1` `*` `36,200,000` = `10,136,000` [source - wp.org](http://wordpress.org/about/stats/)

Receiving an error would require an intersect of old WP and old PHP, so:
`2.6%` of servers running `PHP 4` `*` `10,136,000` = `263,536` sites [source - w3techs](http://w3techs.com/technologies/details/pl-php/all/all) (linked from [php.net](http://php.net/usage.phpa))

**Conclusion**
This error would occur on `0.7%` of WordPress.org installs (`263,536 of 36,200,000`)

## Real-world users

#### Are users installing from Github in that `0.7%`?

No. Absolutely not.

#### Are there other users who might get this plugin loaded on there site?

Yes. Consider [jkudish's GitHub plugin updater](https://github.com/jkudish/WordPress-GitHub-Plugin-Updater): It has `81 forks` and `377 stars`. There are easily dozens of plugins that `include` his library for updates. For example, [Pods](http://wordpress.org/plugins/pods/) used jkudish's library for beta releases.

That's who this check is for — the user who downloads some plugin off of ThemeForest, Google, or a personal blog, unaware that it comes with this library.

#### Machine resources vs. human resources

With that further reach, I think it's reasonable to assume that some stupid site out there might benefit from this. Certainly enough to merit a call to `version_compare`, which takes `0.0000191 seconds` (one fifth of a millisecond). There's certainly not a resources issue here — especially not to save real time for real people.

## Code Revision

If this were just a plugin being installed from Github, I'd say sure — take it out. But, since, like jkudish's library, I'm explicitly saying in the readme, "you can include this in your plugins", I think it's worth being a good steward of all those users who might install those other plugins from anywhere.

Since there are still `200,000` sites this effects, and because there's basically no resources being used by the check, I don't see reason to remove it outright. (I'd also defer to the precedent set by WordPress SEO — Yoast is running active stats on 3 million installs. If he takes the check out of his plugin, I'll endorse removing it here.)

**However...**
After talking it out, I do see the light on @afragen's recommended change. Since the affected audience is users of plugins that use this updater as a library, `wp_die()` (and even deactivating the plugin) don't make sense. I'll go into your pull request and make changes to display an admin notice only.

**Comment by pdclark** [comment]
Well, well, well... I've come full circle. I think you both might like this commit. After working through @afragan's pull request again, I came through several realizations, which ended in simplifying the check down to one line and no extra `if` statements.

From the commit message:

> Because effected users would have this library loaded in other plugins,
> there isn't any point in running `deactivate_plugins` or `wp_die`.
> 
> By requiring WordPress 3.2, we also inherantly require PHP5,
> so check of PHP_VERSION is not needed.
> 
> By checking `$wp_version` outside `gpu_git_plugin_updates_init`, we
> can combine all checks into one `if` statement, and don't need
> to declare `global $wp_version`.
> 
> Because users not running WordPress older than 3.2 _already_ have
> an update nag displaying, there's no point in displaying an
> update notice. Because they're already habitually ignoring upgrades,
> it's okay for this plugin to silently not do anything until
> WordPress core is upgraded.

[complete file](https://github.com/brainstormmedia/git-plugin-updates/blob/ca655dc55ea71e6938ff5cb627d9f68bba81f8c7/git-plugin-updates.php)

Are we good?

**Comment by GaryJones** [comment]
I'd move the conditional to the top of that file - no point in defining stuff if there's a chance they aren't going to be used anyway. Might as well skip over it early.

**Comment by pdclark** [comment]
Awesome, awesome catch. Lets us removed all the `if ( !defined() )` checks too! Might as well only check for the class definition — no reason to check for the `init` function if the class is already defined.

**Comment by afragen** [comment]
Looks good.

**Comment by pdclark** [comment]
Resolved in https://github.com/brainstormmedia/git-plugin-updates/pull/16
