### ISSUE TITLE
Rename plugin.php to git-plugin-updates.php

### ISSUE THREAD

**Issue by pdclark** [pdclark/git-plugin-updates#13]
Quoting @GaryJones:

> The Codex twice suggests using [the plugin slug as the main plugin file name](http://codex.wordpress.org/Writing_a_Plugin#Plugin_Files). I thought there was an optimisation somewhere when looking through all plugin files that came from doing exactly that, but I can't find anything right now. If nothing else, since plugin files can be directly in wp-content/plugins, then having them suitably named has always been the suggestion.

https://github.com/afragen/github-updater/issues/2#issuecomment-27449092

**Comment by pdclark** [comment]
**Codex**
Slug is given as the example, yes. But I don't see it as a recommendation. It's a Wiki — same as any blog tutorial.

**Optimization**
As far as I can see in `get_plugins()`, WP attempts to read headers from [every PHP file in the root plugin directory](https://github.com/WordPress/WordPress/blob/70fd806759b7a18d45950eb2c368e15949f1ef21/wp-admin/includes/plugin.php#L264). It's a micro-optimization, but it would at least be better to assure there's only one `.php` file in the plugin directory, then keep all others in `includes/`.

**Plugin files can be directly in `wp-content/plugins`**
For single-file plugins like `hello.php`, sure. For multi-file plugins? I can't claim there isn't _someone_ out there who will download the zip and copy all files into `wp-content/plugins/`... But by that logic, we should also be prefixing `includes`, `js`, and `css` directories with a slug. :/

**Opinion**
I could be totally off-base on this. I do **like** `plugin.php`, but be as consistent with WordPress standards where possible (and up-to-date!). In this case, I think `$slug.php` is an out-dated standard to support an old time when plugins weren't in folders... But WordPress allows for it to be anything.

I'll solicit input from @pippinsplugins and @krogsgard. If either of them tell me I'm an idiot, I'll drop it.

Reasons for my preference for `plugin.php`, quoted from the previous comment thread:

> - Less redundant: The plugin slug is already used in the plugin folder name (typically).
> - More semantic: Clearly states "this is the main plugin file".
> - Quickly reusable: plugin.php can be quickly copied to a new folder to start a new plugin (one less thing to rename).

**Comment by pippinsplugins** [comment]
I'd recommend `$slug.php`

Couple of main reasons:
1. If the plugin does not have it's own folder, it prevents conflicts with other `plugin.php` plugins.
2. It's immediately clear which file is the main plugin file (though this could be argued either way)
3. I just personally like it better.

I'm not sure there is any real advantage of one over the other when the plugin has its own folder.

**Comment by pdclark** [comment]
These sources are clearly rigged. Who decided to ask these people? Oh yeah... :unamused:

@Krogsgard prefers `$slug.php` too: https://twitter.com/krogsgard/status/395716172613554176

Okaaay...... I'll change it. :sob:

Thanks for the quick input @pippinsplugins and @Krogsgard!

**Comment by GaryJones** [comment]
Be aware however, that changing it will mean that when an update happens, the plugin will not reactivate automatically. WP doesn't rescan the updated plugin directory to see which is now the new main plugin file (probably worth checking if a ticket exists for that), so it tries activating using the old reference.

**Comment by pdclark** [comment]
That's fine. This plugin has been public for 2 days.
