### ISSUE TITLE
Choose which plugins to update via git

### ISSUE THREAD

**Issue by bhargavy** [pdclark/git-plugin-updates#19]
Is it possible to choose which plugins to update via git ? 
i.e can I disable git updates for some plugins.

**Comment by pdclark** [comment]
Right now you can disable updates on a plugin by removing the GIt repo URL from Plugin URI and Git URI headers. I do hope to add a user interface in `wp-admin` soon.

**Comment by pdclark** [comment]
Closing as duplicate of #3
