### ISSUE TITLE
Notice: Undefined index: host, user & pass

### ISSUE THREAD

**Issue by adevade** [pdclark/git-plugin-updates#30]
I get notices on all pages in the admin area for undefined index host, user & pass. 

I'm using WordPress 3.7.1 and the current master branch.

**Comment by afragen** [comment]
Might be related to #24

**Comment by pdclark** [comment]
It is, closing as duplicate.

@afragen Looks like you finished the patch. Merging in now.

@adevade Download the current develop branch for a fix.
